version: '3'
services:
  redis:
    image: redis
    ports: 
      - 6379:6379
  nginx:
    image: nginx:latest
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
    restart: always
    env_file: ${ENV_FILE}
  base:
    image: base
    env_file: ${ENV_FILE}
    build: .
  scraper: 
    image: base
    command: >
       sh -c "yarn workspace scraper start"
    env_file: ${ENV_FILE}
    depends_on: 
      - redis
  backend:
    image: base
    command: >
      sh -c "yarn workspace backend deploy &&
             yarn workspace backend start"
    env_file: ${ENV_FILE}
    ports: 
      - 4000:4000
    depends_on:
      - redis
    restart: always
  frontend:
    image: base
    command: >
      sh -c "yarn workspace frontend start"
    restart: always
    depends_on:
      - backend
    links:
      - backend
    env_file: ${ENV_FILE}
