version: '3'
services:
  redis:
    image: redis:latest
  nginx:
    image: nginx:latest
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    restart: always
    env_file: ${ENV_FILE}
  base:
    image: base
    env_file: ${ENV_FILE}
    build: .
  scraper: 
    build:
      context: ./scraper
    command: >
       sh -c "Xvfb :101 -screen 0 1024x768x16 &
            yarn run start"
    env_file: ${ENV_FILE}
    environment:
      - DISPLAY=:101
  backend:
    image: base
    command: >
      sh -c "yarn workspace backend deploy &&
             yarn workspace backend start"
    env_file: ${ENV_FILE}
    ports: 
      - 4000:4000
    depends_on:
      - prisma
    restart: always
  frontend:
    image: base
    command: >
      sh -c "yarn workspace frontend start"
    restart: always
    depends_on:
      - backend
    env_file: ${ENV_FILE}
